// Generated by CoffeeScript 1.9.3
(function() {
  this.Animator = (function() {
    function Animator() {}

    Animator.animate = function(a, b) {};

    return Animator;

  })();

  this.TileSwap = (function() {
    function TileSwap() {}

    TileSwap.tilesToSwap = [];

    TileSwap.process = function(tile) {
      var firstTile, secondTIle;
      if (this.tilesToSwap.length < 2) {
        return this.tilesToSwap.push(tile);
      } else {
        firstTile = this.tilesToSwap.pop();
        return secondTIle = this.tilesToSwap.pop();
      }
    };

    return TileSwap;

  })();

  $('.number-tile').on('click', function() {
    target;
    var target;
    if ($(event.target).hasClass('number')) {
      target = $(event.target).parent();
    } else if ($(event.target).hasClass('number-tile')) {
      target = event.target;
    }
    return $(target).toggleClass('selected');
  });

}).call(this);

//# sourceMappingURL=index.js.map
