// Generated by CoffeeScript 1.9.3
(function() {
  this.Animator = (function() {
    function Animator() {}

    Animator.animate = function(a, b) {
      var height, length;
      if (a === b) {
        return;
      }
      window.a = a;
      window.b = b;
      $(a).addClass('animating-a');
      $(b).addClass('animating-b');
      length = $(b).offset().left - ($(a).offset().left);
      height = 50;
      $.keyframe.define([
        {
          name: "animation-a-to-b",
          '0%': {
            'transform': "translateX(0px)"
          },
          '100%': {
            'transform': "translateX(" + length + "px)"
          }
        }, {
          name: "animation-b-to-a",
          '0%': {
            'transform': "translateX(0px)"
          },
          '100%': {
            'transform': "translateX(" + (length * -1) + "px)"
          }
        }
      ]);
      $(a).playKeyframe({
        name: 'animation-a-to-b',
        duration: '0.30s',
        timingFunction: 'ease-out',
        delay: '0s',
        iterationCount: '1',
        direction: 'normal',
        fillMode: 'forwards',
        complete: function() {
          var operator;
          operator = $('.animating-a').next();
          $(".animating-b").before($(".animating-a"));
          $(operator).before($(".animating-b"));
          $(".animating-b").removeClass('animating-b');
          $('.animating-a').removeClass('animating-a');
          $('.selected').removeClass('selected');
          return $(a).resetKeyframe(null);
        }
      });
      return $(b).playKeyframe({
        name: 'animation-b-to-a',
        duration: '0.30s',
        timingFunction: 'ease-out',
        delay: '0s',
        iterationCount: '1',
        direction: 'normal',
        fillMode: 'forwards',
        complete: function() {
          return $(b).resetKeyframe(null);
        }
      });
    };

    return Animator;

  })();

  this.TileSwap = (function() {
    function TileSwap() {}

    TileSwap.tilesToSwap = [];

    TileSwap.process = function(tile) {
      var firstTile, secondTile;
      this.tilesToSwap.push(tile);
      if (this.tilesToSwap.length === 2) {
        firstTile = this.tilesToSwap.pop();
        secondTile = this.tilesToSwap.pop();
        return Animator.animate(firstTile, secondTile);
      }
    };

    return TileSwap;

  })();

  $('.number-tile').on('click', function(event) {
    target;
    var target;
    if ($(event.target).hasClass('number')) {
      target = event.target.parentElement;
    } else if ($(event.target).hasClass('number-tile')) {
      target = event.target;
    }
    $(target).toggleClass('swappable');
    return TileSwap.process(target);
  });

  $('.number-tile').on('dblclick', function(event) {
    target;
    var target;
    if ($(event.target).hasClass('number')) {
      target = event.target.parentElement;
    } else if ($(event.target).hasClass('number-tile')) {
      target = event.target;
    }
    $(target).toggleClass('enclosable');
    return TileSwap.process(target);
  });

}).call(this);

//# sourceMappingURL=index.js.map
